import { App, PluginSettingTab, Setting } from "obsidian";
import type AKFPlugin from "./main";

export interface AKFSettings {
  frontmatterKey: string;
  checkSidecar: boolean;
  defaultAgent: string;
  defaultTrust: number;
  defaultClassification: string;
  defaultAiGenerated: boolean;
  showStatusBar: boolean;
  graphColoring: "css" | "off";
  trustThresholds: { high: number; medium: number };
}

export const DEFAULT_SETTINGS: AKFSettings = {
  frontmatterKey: "akf",
  checkSidecar: true,
  defaultAgent: "obsidian",
  defaultTrust: 0.7,
  defaultClassification: "internal",
  defaultAiGenerated: true,
  showStatusBar: true,
  graphColoring: "css",
  trustThresholds: { high: 0.8, medium: 0.5 },
};

export class AKFSettingTab extends PluginSettingTab {
  plugin: AKFPlugin;

  constructor(app: App, plugin: AKFPlugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display(): void {
    const { containerEl } = this;
    containerEl.empty();

    containerEl.createEl("h2", { text: "AKF — Agent Knowledge Format" });

    new Setting(containerEl)
      .setName("Frontmatter key")
      .setDesc('YAML key used for AKF metadata (e.g., "akf" or "_akf")')
      .addText((text) =>
        text
          .setPlaceholder("akf")
          .setValue(this.plugin.settings.frontmatterKey)
          .onChange(async (value) => {
            this.plugin.settings.frontmatterKey = value || "akf";
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Check sidecar files")
      .setDesc("Also look for .akf.json sidecar files alongside notes")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.checkSidecar)
          .onChange(async (value) => {
            this.plugin.settings.checkSidecar = value;
            await this.plugin.saveSettings();
          })
      );

    containerEl.createEl("h3", { text: "Stamp Defaults" });

    new Setting(containerEl)
      .setName("Default agent")
      .setDesc("Agent name used when quick-stamping notes")
      .addText((text) =>
        text
          .setPlaceholder("obsidian")
          .setValue(this.plugin.settings.defaultAgent)
          .onChange(async (value) => {
            this.plugin.settings.defaultAgent = value || "obsidian";
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Default trust score")
      .setDesc("Trust score (0.0 - 1.0) for quick-stamping")
      .addSlider((slider) =>
        slider
          .setLimits(0, 1, 0.05)
          .setValue(this.plugin.settings.defaultTrust)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.defaultTrust = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Default classification")
      .setDesc("Security classification for quick-stamping")
      .addDropdown((dropdown) =>
        dropdown
          .addOption("public", "Public")
          .addOption("internal", "Internal")
          .addOption("confidential", "Confidential")
          .addOption("restricted", "Restricted")
          .setValue(this.plugin.settings.defaultClassification)
          .onChange(async (value) => {
            this.plugin.settings.defaultClassification = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Default AI-generated flag")
      .setDesc("Mark notes as AI-generated by default when stamping")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.defaultAiGenerated)
          .onChange(async (value) => {
            this.plugin.settings.defaultAiGenerated = value;
            await this.plugin.saveSettings();
          })
      );

    containerEl.createEl("h3", { text: "Display" });

    new Setting(containerEl)
      .setName("Show status bar")
      .setDesc("Show trust badge in the bottom status bar")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.showStatusBar)
          .onChange(async (value) => {
            this.plugin.settings.showStatusBar = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Graph coloring")
      .setDesc("Color graph nodes by trust level")
      .addDropdown((dropdown) =>
        dropdown
          .addOption("css", "Enabled (CSS injection)")
          .addOption("off", "Disabled")
          .setValue(this.plugin.settings.graphColoring)
          .onChange(async (value) => {
            this.plugin.settings.graphColoring = value as "css" | "off";
            await this.plugin.saveSettings();
          })
      );

    containerEl.createEl("h3", { text: "Trust Thresholds" });

    new Setting(containerEl)
      .setName("High trust threshold")
      .setDesc("Score at or above this is considered high trust")
      .addSlider((slider) =>
        slider
          .setLimits(0.5, 1, 0.05)
          .setValue(this.plugin.settings.trustThresholds.high)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.trustThresholds.high = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Medium trust threshold")
      .setDesc("Score at or above this is considered medium trust")
      .addSlider((slider) =>
        slider
          .setLimits(0.1, 0.8, 0.05)
          .setValue(this.plugin.settings.trustThresholds.medium)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.trustThresholds.medium = value;
            await this.plugin.saveSettings();
          })
      );
  }
}
